product_database = [
{
        "name": "Beauty of Joseon Relief Sun: Rice + Probiotics SPF50+",
        "description": "A lightweight sunscreen that moisturises and protects the skin.",
        "detailed_description": "A lightweight, hydrating sunscreen that provides high SPF50+ protection while helping to moisturise and nourish the skin. It contains rice extract and fermented grain extracts, which help support a healthy-looking complexion, while niacinamide helps brighten the appearance of dull skin. Its moisturising formula makes it suitable for a range of skin types, including dry, combination, sensitive, and oily skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["dry", "dull", "sensitive", "fine lines"],
        "price": 31.00,
        "key_ingredients": "Rice extract, grain fermented extracts, niacinamide, Alcohol",
        "image": "images/boj_sunscreen.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/relief-sun-rice-probiotics?srsltid=AfmBOorIplhPdfF1Qi0sjb3y_uDV53hr9rZQY4syB09fEbwY59LTg3Np"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/beauty-of-joseon-relief-sun-rice-probiotics-50ml/info.html/pid.1137908658"},]
    },
    {
        "name": "COSRX Acne Pimple Master Patch",
        "description": "Pimple patches that protect spots and help reduce breakouts.",
        "detailed_description": "Hydrocolloid pimple patches designed to cover and protect blemishes from dirt and external irritation. The patches help absorb fluid from spots while creating a protective barrier over the affected area. They are a simple, targeted option for people who experience occasional breakouts and want to help protect individual blemishes.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["acne"],
        "price": 6.00,
        "key_ingredients": "Hydrocolloid patch",
        "image": "images/cosrx_pimple_patch.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/acne-pimple-master-patch?variant=27927811137&country=NZ&currency=NZD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&gad_source=1&gad_campaignid=21428164992&gbraid=0AAAAADfsQE2s_JG1voCwWg81ufLX94pp9&gclid=Cj0KCQjw-frTBhCvARIsADv4XY4pTz9bAV6oVPQ5BsMeZ4_GR04dndhhdyLqqPaney18R8y6TJmg2uEaAgfNEALw_wcB"},
                        {"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/cosrx-acne-pimple-master-patch-24patches-1"}]
    },
    {
        "name": "Dr.Althea 345 Relief Cream",
        "description": "A soothing cream for irritated, dry, or sensitive skin.",
        "detailed_description": "A soothing moisturiser designed to provide hydration and comfort to dry, irritated, and sensitive-looking skin. The formula contains niacinamide, panthenol, and centella asiatica, which help support the skin barrier and calm the appearance of redness and irritation. Its nourishing texture makes it particularly suitable for dry and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["dry", "sensitive", "texture", "acne"],
        "price": 45.00,
        "key_ingredients": "Niacinamide, panthenol, centella asiatica",
        "image": "images/dr_althea_345.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/345-relief-cream?_pos=1&_sid=5c732f124&_ss=r"},
                         {"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/dr-althea-345-relief-cream?_pos=1&_sid=81773dac8&_ss=r"}]
    },
    {
        "name": "ANUA Heartleaf Quercetinol Pore Deep Cleansing Foam",
        "description": "A cleanser that helps remove oil, dirt, and pore buildup.",
        "detailed_description": "A gentle foaming cleanser designed to remove excess oil, dirt, and impurities that can build up within pores. It contains heartleaf extract and quercetinol to help soothe the skin, while hyaluronic acid helps maintain hydration during cleansing. It is particularly suited to oily, combination, and sensitive skin types and can be useful for skin concerned with clogged pores and texture.",
        "suitable_skin_types": ["oily", "combination", "sensitive"],
        "targeted_skin_concerns": ["acne", "clogged pores", "texture", "sensitive"],
        "price": 28.00,
        "key_ingredients": "Heartleaf extract, quercetinol, hyaluronic acid",
        "image": "images/anua_heartleaf_cleanser.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/heartleaf-quercetinol-pore-deep-cleansing-foam?_pos=1&_sid=f103eac01&_ss=r"},
                         {"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/search?options%5Bprefix%5D=last&q=anua+foam+cleanser"}]
    },
    {
        "name": "ANUA Niacinamide 10% + TXA 4% Serum",
        "description": "A serum that helps brighten uneven and dull-looking skin.",
        "detailed_description": "A brightening serum formulated with 10% niacinamide and 4% tranexamic acid to help improve the appearance of dull and uneven-looking skin. Niacinamide can help support the skin barrier and improve the appearance of pores, while tranexamic acid is commonly used in skincare targeting uneven pigmentation. The lightweight formula is suitable for normal, oily, and combination skin types.",
        "suitable_skin_types": ["normal", "oily", "combination"],
        "targeted_skin_concerns": ["dull", "texture", "clogged pores"],
        "price": 44.00,
        "key_ingredients": "Niacinamide, tranexamic acid",
        "image": "images/anua_niacinamide_serum.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/niacinamide-10-txa-4-dark-spot-correcting-serum?_pos=1&_sid=41c5c853d&_ss=r"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/anua-niacinamide-10-txa-4-serum-2024-version-30ml/info.html/pid.1132942898"}]
    },
    {
        "name": "COSRX Low pH Good Morning Gel Cleanser",
        "description": "A gentle everyday cleanser for keeping skin balanced.",
        "detailed_description": "A low-pH gel cleanser designed for gentle everyday cleansing while helping maintain the skin's natural balance. It contains tea tree leaf oil and betaine salicylate, which help remove excess oil and impurities from the skin. The cleanser is suitable for normal, oily, combination, and sensitive skin types and can be useful for skin experiencing breakouts or uneven texture.",
        "suitable_skin_types": ["normal", "oily", "combination", "sensitive"],
        "targeted_skin_concerns": ["acne", "texture", "sensitive"],
        "price": 16.90,
        "key_ingredients": "Tea tree leaf oil, betaine salicylate, Fragrance",
        "image": "images/cosrx_gel_cleanser.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/low-ph-good-morning-gel-cleanser?_pos=1&_sid=a6d871858&_ss=r"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/cosrx-low-ph-good-morning-gel-cleanser-150ml/info.html/pid.1052684732"}]
    },
    {
        "name": "ROUND LAB 1025 Dokdo Cleanser",
        "description": "A gentle cleanser that cleans skin without stripping moisture.",
        "detailed_description": "A gentle facial cleanser designed to remove dirt, excess oil, and impurities without leaving the skin feeling excessively dry or stripped. It contains deep sea water along with panthenol and allantoin to help maintain hydration and comfort. Its mild formula makes it suitable for normal, dry, combination, and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["dry", "sensitive", "texture"],
        "price": 19.00,
        "key_ingredients": "Deep sea water, panthenol, allantoin",
        "image": "images/roundlab_dokdo_cleanser.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/1025-dokdo-cleanser?_pos=1&_sid=e9413db55&_ss=r"},
                         {"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/round-lab-1025-dokdo-cleanser-150ml?_pos=1&_sid=5cb36c87f&_ss=r"}]
    },
    {
        "name": "COSRX Advanced Snail 96 Mucin Power Essence",
        "description": "A hydrating essence that helps smooth texture and support the skin barrier.",
        "detailed_description": "A hydrating essence containing 96% snail secretion filtrate to help moisturise and improve the appearance of dry or uneven skin. The formula also contains betaine and allantoin, which help support hydration and soothe the skin. Its lightweight texture can be layered into a skincare routine and is suitable for all skin types, including sensitive and oily skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["dry", "texture", "sensitive", "fine lines"],
        "price": 12.00,
        "key_ingredients": "Snail secretion filtrate, betaine, allantoin",
        "image": "images/cosrx_snail_essence.png",
        "where_to_buy": [{"name": "W cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/cosrx-advanced-snail-96-mucin-power-essence?_pos=1&_sid=2da0e9fe9&_ss=r"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/cosrx-advanced-snail-96-mucin-power-essence-100ml/info.html/pid.1052684695"}]
    },
    {
        "name": "Torriden Dive-In Low Molecule Hyaluronic Acid Serum",
        "description": "A lightweight hydrating serum for dry or dehydrated skin.",
        "detailed_description": "A lightweight hydrating serum formulated with low molecular hyaluronic acid to help replenish moisture and improve the appearance of dehydrated skin. Panthenol and allantoin provide additional soothing and moisturising support. The lightweight texture makes it suitable for all skin types and particularly useful for skin experiencing dryness, dullness, or sensitivity.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["dry", "dull", "sensitive"],
        "price": 32.00,
        "key_ingredients": "Low molecular hyaluronic acid, panthenol, allantoin",
        "image": "images/torriden_hyaluronic_serum.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/dive-in-low-molecular-hyaluronic-acid-serum?_pos=1&_sid=2a9a2cff0&_ss=r"},
                        {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/torriden-dive-in-low-molecular-hyaluronic-acid-serum-renewed-50ml/info.html/pid.1115692618"}]
    },
    {
        "name": "Skin1004 Madagascar Centella Ampoule",
        "description": "A calming ampoule that helps soothe sensitive or irritated skin.",
        "detailed_description": "A lightweight calming ampoule centred around centella asiatica extract, an ingredient commonly used to soothe and support sensitive-looking skin. The simple formula is designed to provide hydration while helping the skin feel calmer and more comfortable. It is suitable for all skin types and can be particularly useful for people concerned with sensitivity, blemishes, and uneven texture.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["sensitive", "acne", "texture"],
        "price": 29.00,
        "key_ingredients": "Centella asiatica extract",
        "image": "images/skin1004_centella_ampoule.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/madagascar-centella-ampoule?_pos=2&_psq=centella&_psid=3b99bd9f2&_ss=e"},
                         {"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/skin1004-madagascar-centella-ampoule-55ml?_pos=1&_sid=16b000620&_ss=r"}]
    },
    {
        "name": "Beauty of Joseon Dynasty Cream",
        "description": "A moisturising cream that helps with dryness and dull skin.",
        "detailed_description": "A nourishing moisturising cream designed to hydrate the skin and improve the appearance of dryness and dullness. It contains rice bran water, ginseng root water, and niacinamide, which help support a moisturised and healthy-looking complexion. The richer formula is particularly suitable for normal, dry, combination, and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["dry", "dull", "fine lines"],
        "price": 41.90,
        "key_ingredients": "Rice bran water, ginseng root water, niacinamide, Fragrance",
        "image": "images/boj_dynasty_cream.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/dynasty-cream?_pos=1&_sid=4f348f2a1&_ss=r"},
                         {"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/beauty-of-joseon-dynasty-cream-50ml?_pos=2&_psq=dynasty+cream&_psid=cc0ae45cd&_ss=e"}]
    },
    {
        "name": "Beauty of Joseon Glow Serum: Propolis + Niacinamide",
        "description": "A glow serum that helps with dullness, texture, and blemish-prone skin.",
        "detailed_description": "A lightweight glow-focused serum formulated with propolis extract and niacinamide to help improve the appearance of dull, uneven, and blemish-prone skin. Propolis helps provide a nourishing feel, while niacinamide supports the skin barrier and helps improve the appearance of pores. The serum is suitable for normal, oily, combination, and sensitive skin types.",
        "suitable_skin_types": ["normal", "oily", "combination", "sensitive"],
        "targeted_skin_concerns": ["dull", "texture", "acne"],
        "price": 38.00,
        "key_ingredients": "Propolis extract, niacinamide",
        "image": "images/boj_glow_serum.png",
        "where_to_buy": [{"name": "W Cosmetics", "logo": "images/w_cosmetics_logo.png", "link": "https://wcosmetics.com.au/products/foc-beauty-of-joseon-glow-serum-propolis-niacinamide-60ml?_pos=2&_sid=e19bed863&_ss=r"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/beauty-of-joseon-glow-serum-jumbo-60ml/info.html/pid.1133657599"}]
    },
        {
        "name": "Medicube Deep Vita A Retinol Serum",
        "description": "A retinol serum designed to improve the appearance of fine lines, uneven texture, and signs of skin ageing.",
        "detailed_description": "A retinol-based serum designed to target the appearance of fine lines, uneven texture, visible pores, and signs of skin ageing. It combines retinol with niacinamide, hyaluronic acid, and ceramides to provide skincare benefits alongside hydration and barrier support. It is suitable for normal, dry, combination, and oily skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "oily"],
        "targeted_skin_concerns": ["fine lines", "texture", "dull", "clogged pores"],
        "price": 40.95,
        "key_ingredients": "Retinol, niacinamide, hyaluronic acid, ceramides",
        "image": "images/medicube_retinol_serum.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/deep-vita-a-retinol-serum?srsltid=AfmBOooeY4EsY5jmTl95b43oEwKnFnquUqDArdp4UU1mIDGxiCUHGzgl"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/medicube-deep-vita-a-retinol-serum-30ml/info.html/pid.1129540918"}]
    },
    {
        "name": "Anua Retinol 0.3% + Niacin Renewing Serum",
        "description": "A renewing serum combining retinol and niacinamide to improve the appearance of pores, uneven texture, and fine lines.",
        "detailed_description": "A renewing serum containing 0.3% retinol and niacinamide to target the appearance of fine lines, visible pores, uneven texture, and dullness. Ceramides and hyaluronic acid help provide additional hydration and support for the skin barrier. The formula is designed for normal, oily, and combination skin types.",
        "suitable_skin_types": ["normal", "oily", "combination"],
        "targeted_skin_concerns": ["fine lines", "clogged pores", "texture", "dull"],
        "price": 53.10,
        "key_ingredients": "Retinol, niacinamide, ceramides, hyaluronic acid",
        "image": "images/anua_retinol_serum.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/anua-retinol-0-3-niacin-renewing-serum?srsltid=AfmBOoplEy9tWL2RCGeZhNWwtXr8sNMtrKkcGb0bImR3NEUjuRJK1u-8"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/anua-retinol-0-3-niacin-renewing-serum-30ml/info.html/pid.1133093776"}]
    },
    {
        "name": "celimax The Vita-A Retinol Shot Tightening Serum",
        "description": "A targeted retinol serum designed to improve the appearance of pores, fine lines, and uneven skin texture.",
        "detailed_description": "A targeted retinol serum designed to improve the appearance of pores, fine lines, uneven texture, and dull-looking skin. It combines retinol with niacinamide, peptides, and hyaluronic acid to provide a combination of smoothing and hydrating skincare benefits. It is suitable for normal, oily, and combination skin types.",
        "suitable_skin_types": ["normal", "oily", "combination"],
        "targeted_skin_concerns": ["fine lines", "clogged pores", "texture", "dull"],
        "price": 34.00,
        "key_ingredients": "Retinol, niacinamide, peptides, hyaluronic acid",
        "image": "images/celimax_retinol_serum.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/the-vita-a-retinol-shot-tightening-serum?srsltid=AfmBOoqkvQCUn2-9iVQaTZaI01mTCYqr_FegfPJVg_x5dTvj47jJNape"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/celimax-the-vita-a-retinol-shot-tightening-serum-30ml/info.html/pid.1130946338"}]
    },
    {
        "name": "Innisfree Retinol Cica Repair Ampoule",
        "description": "A soothing retinol ampoule designed to improve uneven texture while helping support the skin barrier.",
        "detailed_description": "A retinol ampoule designed to target uneven texture and the appearance of fine lines while providing soothing and barrier-supporting ingredients. The formula combines retinol with cica, niacinamide, and hyaluronic acid to help moisturise and comfort the skin. It is suitable for normal, dry, combination, and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["fine lines", "texture", "sensitive", "acne"],
        "price": 62.10,
        "key_ingredients": "Retinol, cica, niacinamide, hyaluronic acid, Alcohol, Fragrance",
        "image": "images/innisfree_retinol_cica.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/retinol-cica-repair-ampoule?srsltid=AfmBOor7ALMBhU9cm1bPOBrKd2lRFiZgTmUBFSIdo8r3DHEpisquL1WF"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/innisfree-retinol-cica-repair-ampoule-renewal-version-30ml/info.html/pid.1120887566"}]
    },
    {
        "name": "Haruharu Wonder Black Rice Bakuchiol Eye Cream",
        "description": "A nourishing eye cream designed to improve the appearance of fine lines and dryness around the eye area.",
        "detailed_description": "A nourishing eye cream formulated with fermented black rice extract, bakuchiol, and adenosine to care for the delicate skin around the eyes. It helps moisturise the eye area while targeting the appearance of fine lines, dryness, and dullness. Its nourishing formula is suitable for normal, dry, combination, and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["fine lines", "dry", "dull"],
        "price": 28.00,
        "key_ingredients": "Fermented black rice extract, bakuchiol, adenosine",
        "image": "images/haruharu_eye_cream.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/black-rice-bakuchiol-eye-cream?srsltid=AfmBOooesvR2yu7q9cA0H0ANWuRnUEQZLm1FayqLFABJY3ril7KykEaC"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/haruharu-wonder-black-rice-bakuchiol-eye-cream-20ml/info.html/pid.1112455824"}]
    },
    {
        "name": "Purito SEOUL Retinol Retinal 2000 NAD+ Serum",
        "description": "An anti-ageing serum containing retinol and retinal designed to improve the appearance of fine lines and uneven texture.",
        "detailed_description": "An anti-ageing focused serum combining retinol, retinal, NAD+, peptides, and niacinamide to target the appearance of fine lines, uneven texture, and dull-looking skin. The combination of ingredients is designed to provide smoothing and skin-supporting benefits while helping maintain hydration. It is suitable for normal, dry, and combination skin types.",
        "suitable_skin_types": ["normal", "dry", "combination"],
        "targeted_skin_concerns": ["fine lines", "texture", "dull"],
        "price": 37.80,
        "key_ingredients": "Retinol, retinal, NAD+, peptides, niacinamide",
        "image": "images/purito_retinol_retinal_serum.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/retinol-retinal-2000-nad-serum?srsltid=AfmBOooWngVFSgH1sa2VR3CG3upd9eXJH31nkdtg9tKLVRfJO4rhoUh8"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/purito-seoul-retinol-retinal-2000-nad-serum-30ml/info.html/pid.1137538142"}]
    },
    {
        "name": "Seoul 1988 Serum: Retinal Liposome 2% + Black Ginseng",
        "description": "A retinal serum designed to improve the appearance of fine lines, uneven texture, pores, and dull skin.",
        "detailed_description": "A retinal-focused serum designed to improve the appearance of fine lines, uneven texture, visible pores, and dullness. It combines retinal with black ginseng extract, bakuchiol, niacinamide, and peptides to provide a range of skin-smoothing and nourishing benefits. The formula is suitable for normal, dry, combination, oily, and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "oily", "sensitive"],
        "targeted_skin_concerns": ["fine lines", "texture", "clogged pores", "dull"],
        "price": 37.00,
        "key_ingredients": "Retinal, black ginseng extract, bakuchiol, niacinamide, peptides",
        "image": "images/seoul_1988_retinal.png",
        "where_to_buy": [{"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/seoul-1988-serum-retinal-liposome-2-black-ginseng?srsltid=AfmBOooSgDoMtZrA2zkS9_N13A8vZGUPhk5uYM4sj1ABE29iFAqeLXKq"},
                         {"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/ksecret-seoul-1988-serum-retinal-liposome-2-black-ginseng-30ml/info.html/pid.1126934079"}]
    },
    {
        "name": "APLB Spicule Retinol Shot 180 Serum",
        "description": "A retinol serum with centella and soothing ingredients designed to improve the appearance of texture and signs of ageing.",
        "detailed_description": "A retinol serum formulated with centella asiatica, panthenol, squalane, and beta-glucan to target the appearance of fine lines and uneven texture while providing soothing and moisturising support. The combination of retinol and skin-conditioning ingredients is designed for normal, dry, combination, and sensitive skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["fine lines", "texture", "dry", "sensitive"],
        "price": 16.60,
        "key_ingredients": "Retinol, centella asiatica, panthenol, squalane, beta-glucan",
        "image": "images/aplb_retinol_serum.png",
        "where_to_buy": [{"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/aplb-spicule-retinol-shot-180-serum-40ml/info.html/pid.1133553915"}]
    },
    {
        "name": "APLB Coenzyme Q10 Retinol Ampoule Serum",
        "description": "A retinol ampoule designed to improve the appearance of dullness, pores, and fine lines while providing hydration.",
        "detailed_description": "A retinol ampoule designed to target the appearance of fine lines, dullness, visible pores, and uneven texture. It combines retinol with coenzyme Q10, squalane, and hyaluronic acid to provide smoothing and hydrating skincare benefits. The formula is suitable for normal, dry, combination, and oily skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "oily"],
        "targeted_skin_concerns": ["fine lines", "dull", "clogged pores", "texture"],
        "price": 16.60,
        "key_ingredients": "Retinol, coenzyme Q10, squalane, hyaluronic acid",
        "image": "images/aplb_q10_retinol.png",
        "where_to_buy": [{"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/aplb-coenzyme-q10-retinol-ampoule-serum-40ml/info.html/pid.1130147937"}]
    },
    {
        "name": "APLB Retinol Vitamin C Vitamin E Ampoule Serum",
        "description": "A brightening and anti-ageing ampoule containing retinol, vitamin C, and vitamin E.",
        "detailed_description": "A brightening and anti-ageing focused ampoule combining retinol, vitamin C, vitamin E, and centella asiatica. The formula is designed to improve the appearance of dullness, uneven texture, and fine lines while providing antioxidant and soothing skincare benefits. It is suitable for normal, dry, and combination skin types.",
        "suitable_skin_types": ["normal", "dry", "combination"],
        "targeted_skin_concerns": ["fine lines", "dull", "texture"],
        "price": 16.00,
        "key_ingredients": "Retinol, vitamin C, vitamin E, centella asiatica",
        "image": "images/aplb_retinol_vitamin_serum.png",
        "where_to_buy": [{"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/aplb-retinol-vitamin-c-vitamin-e-ampoule-serum-40ml/info.html/pid.1125409748"},
                         {"name": "HIKOCO", "logo": "images/hikoco_logo.png", "link": "https://hikoco.co.nz/products/retinol-vitamin-c-vitamin-e-ampoule-serum?srsltid=AfmBOopUJXZlu8RqKUemiYmzQAY0aWse8zmRN5G7jK3gzRmVsPvFnW6v"}]
    },
    {
        "name": "Bellflower Retinol 0.3% Serum",
        "description": "A Korean retinol serum designed to improve the appearance of fine lines, uneven texture, and signs of skin ageing.",
        "detailed_description": "A retinol serum containing 0.3% retinol and additional plant extracts and hyaluronic acid to target the appearance of fine lines, uneven texture, and dull-looking skin. The formula combines retinol's smoothing properties with hydrating ingredients to help maintain a moisturised complexion. It is suitable for normal, dry, combination, and oily skin types.",
        "suitable_skin_types": ["normal", "dry", "combination", "oily"],
        "targeted_skin_concerns": ["fine lines", "texture", "dull"],
        "price": 20.00,
        "key_ingredients": "Retinol, plant extracts, hyaluronic acid",
        "image": "images/bellflower_retinol.png",
        "where_to_buy": [{"name": "YesStyle", "logo": "images/yesstyle_logo.png", "link": "https://www.yesstyle.com/en/bellflower-retinol-0-3-serum-30ml/info.html/pid.1134621943"}]
    }
]