product_database = [
{
        "name": "Beauty of Joseon Relief Sun: Rice + Probiotics SPF50+",
        "description": "A lightweight sunscreen that moisturises and protects the skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["dry", "dull", "sensitive", "fine lines"],
        "price": 31.90,
        "key_ingredients": "Rice extract, grain fermented extracts, niacinamide",
    },
    {
        "name": "COSRX Acne Pimple Master Patch",
        "description": "Pimple patches that protect spots and help reduce breakouts.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["acne"],
        "price": 6.90,
        "key_ingredients": "Hydrocolloid patch",
    },
    {
        "name": "Dr.Althea 345 Relief Cream",
        "description": "A soothing cream for irritated, dry, or sensitive skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["dry", "sensitive", "texture", "acne"],
        "price": 49.90,
        "key_ingredients": "Niacinamide, panthenol, centella asiatica",
    },
    {
        "name": "ANUA Heartleaf Quercetinol Pore Deep Cleansing Foam",
        "description": "A cleanser that helps remove oil, dirt, and pore buildup.",
        "suitable_skin_types": ["oily", "combination", "sensitive"],
        "targeted_skin_concerns": ["acne", "clogged pores", "texture", "sensitive"],
        "price": 22.90,
        "key_ingredients": "Heartleaf extract, quercetinol, hyaluronic acid",
    },
    {
        "name": "ANUA Niacinamide 10% + TXA 4% Serum",
        "description": "A serum that helps brighten uneven and dull-looking skin.",
        "suitable_skin_types": ["normal", "oily", "combination"],
        "targeted_skin_concerns": ["dull", "texture", "clogged pores"],
        "price": 43.90,
        "key_ingredients": "Niacinamide, tranexamic acid",
    },
    {
        "name": "COSRX Low pH Good Morning Gel Cleanser",
        "description": "A gentle everyday cleanser for keeping skin balanced.",
        "suitable_skin_types": ["normal", "oily", "combination", "sensitive"],
        "targeted_skin_concerns": ["acne", "texture", "sensitive"],
        "price": 16.90,
        "key_ingredients": "Tea tree leaf oil, betaine salicylate",
    },
    {
        "name": "ROUND LAB 1025 Dokdo Cleanser",
        "description": "A gentle cleanser that cleans skin without stripping moisture.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["dry", "sensitive", "texture"],
        "price": 19.90,
        "key_ingredients": "Deep sea water, panthenol, allantoin",
    },
    {
        "name": "COSRX Advanced Snail 96 Mucin Power Essence",
        "description": "A hydrating essence that helps smooth texture and support the skin barrier.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["dry", "texture", "sensitive", "fine lines"],
        "price": 29.00,
        "key_ingredients": "Snail secretion filtrate, betaine, allantoin",
    },
    {
        "name": "Torriden Dive-In Low Molecule Hyaluronic Acid Serum",
        "description": "A lightweight hydrating serum for dry or dehydrated skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["dry", "dull", "sensitive"],
        "price": 12.80,
        "key_ingredients": "Low molecular hyaluronic acid, panthenol, allantoin",
    },
    {
        "name": "Skin1004 Madagascar Centella Ampoule",
        "description": "A calming ampoule that helps soothe sensitive or irritated skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive", "oily"],
        "targeted_skin_concerns": ["sensitive", "acne", "texture"],
        "price": 10.50,
        "key_ingredients": "Centella asiatica extract",
    },
    {
        "name": "Beauty of Joseon Dynasty Cream",
        "description": "A moisturising cream that helps with dryness and dull skin.",
        "suitable_skin_types": ["normal", "dry", "combination", "sensitive"],
        "targeted_skin_concerns": ["dry", "dull", "fine lines"],
        "price": 41.90,
        "key_ingredients": "Rice bran water, ginseng root water, niacinamide",
    },
    {
        "name": "Beauty of Joseon Glow Serum: Propolis + Niacinamide",
        "description": "A glow serum that helps with dullness, texture, and blemish-prone skin.",
        "suitable_skin_types": ["normal", "oily", "combination", "sensitive"],
        "targeted_skin_concerns": ["dull", "texture", "acne"],
        "price": 29.90,
        "key_ingredients": "Propolis extract, niacinamide",
    }
]